version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          command: |
            docker run --name=raid -e MYSQL_ROOT_PASSWORD=1234 -e MYSQL_DATABASE=raid -p 6603:3306 -d mysql:latest
            docker run --name=redis -p 6604:6379 -d redis:latest
      - run:
          command: |
            mkdir ./src/main/resources
            touch ./src/main/resources/application.properties
            touch ./gradle/wrapper/gradle-wrapper.properties
      - run:
          command: |
            echo "distributionBase = ${distributionBase}" >> ./gradle/wrapper/gradle-wrapper.properties
            echo "distributionPath = ${distributionPath}" >> ./gradle/wrapper/gradle-wrapper.properties
            echo "distributionUrl = ${distributionUrl}" >> ./gradle/wrapper/gradle-wrapper.properties
            echo "zipStoreBase = ${zipStoreBase}" >> ./gradle/wrapper/gradle-wrapper.properties
            echo "zipStorePath = ${zipStorePath}" >> ./gradle/wrapper/gradle-wrapper.properties
            
            echo "spring.datasource.url = ${spring_datasource_url}" >> ./src/main/resources/application.properties
            echo "spring.datasource.username = ${spring_datasource_username}" >> ./src/main/resources/application.properties
            echo "spring.datasource.password = ${spring_datasource_password}" >> ./src/main/resources/application.properties
            echo "spring.jpa.show-sql = ${spring_jpa_show_sql}" >> ./src/main/resources/application.properties
            echo "spring.session.jdbc.initialize-schema = ${spring_session_jdbc_initialize_schema}" >> ./src/main/resources/application.properties
            echo "spring.datasource.driver-class-name = ${spring_datasource_driver_class_name}" >> ./src/main/resources/application.properties
            echo "spring.jpa.database-platform = ${spring_jpa_database_platform}" >> ./src/main/resources/application.properties
            echo "spring.jpa.generate-ddl = ${spring_jpa_generate_ddl}" >> ./src/main/resources/application.properties

            echo "spring.redis.port = ${spring_redis_port}" >> ./src/main/resources/application.properties
            echo "spring.redis.host = ${spring_redis_host}" >> ./src/main/resources/application.properties

      - run: ./gradlew clean
      - run: ./gradlew build --no-build-cache --debug
      - run: ./gradlew test

workflows:
  build_and_test:
    jobs:
      - build
