version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          command: |
            touch ./gradle/wrapper/gradle-wrapper.properties
            echo "distributionBase=${distributionBase}" >> ./gradle/wrapper/gradle-wrapper.properties
            echo "distributionPath=${distributionPath}" >> ./gradle/wrapper/gradle-wrapper.properties
            echo "distributionUrl=${distributionUrl}" >> ./gradle/wrapper/gradle-wrapper.properties
            echo "zipStoreBase=${zipStoreBase}" >> ./gradle/wrapper/gradle-wrapper.properties
            echo "zipStorePath=${zipStorePath}" >> ./gradle/wrapper/gradle-wrapper.properties
      - run: ./gradlew build

workflows:
  build_and_test:
    jobs:
      - build
